//! Empty-project intent is resolved before it can become a publication candidate.
use super::documents::DocumentCodec;
use anyhow::{Result, ensure};
use empack_core::{
    files::{ManagedPath, ProjectScaffold},
    model::{ProjectIntent, ResolutionLock, ResolvedProject, RuntimeResolution},
    path::{PathSyntax, PortableRelPath},
};
use std::collections::BTreeMap;

/// Semantic initialization accepts an exact runtime selection from the host's resolver.
/// This validates coherence, not remote availability; runtime acquisition verifies provider
/// declarations and bytes before a build can publish an executable distribution.
pub struct InitializeCandidate {
    project: ResolvedProject,
    templates: BTreeMap<PortableRelPath, Vec<u8>>,
    scaffolds: BTreeMap<ManagedPath, Vec<u8>>,
    publication_bytes: u64,
}
impl InitializeCandidate {
    /// Templates are relative to templates/. Existing user files at these paths are preserved.
    /// Scripts are generated by the selected build recipe; scaffolding never installs stale
    /// bootstrap commands that bypass its exact tool selections.
    pub fn new(
        intent: ProjectIntent,
        runtime: RuntimeResolution,
        templates: BTreeMap<PortableRelPath, Vec<u8>>,
    ) -> Result<Self> {
        ensure!(
            intent.roots.is_empty(),
            "Initialization cannot omit dependency resolution"
        );
        let bytes = DocumentCodec.encode_intent(&intent)?;
        let decoded = DocumentCodec.decode_intent(&bytes, "initialization")?;
        let revision = decoded.semantic_revision();
        let project = ResolvedProject::validate(
            intent,
            ResolutionLock {
                acceptable_versions: decoded.intent().runtime.acceptable_versions.clone(),
                intent_revision: revision,
                resolver: "empack-initialize-v0.5".into(),
                dependencies: BTreeMap::new(),
                required_edges: BTreeMap::new(),
                coverage: BTreeMap::new(),
                runtime,
            },
            revision,
        )?;
        let mut collisions = super::layout::CollisionIndex::default();
        let mut outputs = BTreeMap::<_, super::layout::CollisionIndex>::new();
        let mut publication_bytes =
            bytes.len() as u64 + DocumentCodec.encode_lock(&project)?.len() as u64;
        for (path, bytes) in &templates {
            ensure!(
                path.as_str()
                    .split_once('/')
                    .is_some_and(
                        |(side, tail)| matches!(side, "common" | "client" | "server")
                            && !tail.is_empty()
                    ),
                "Template must belong to a common, client or server layer"
            );
            collisions.insert_file(path)?;
            let (layer, destination, _) = super::templates::template_address(path.as_str())?
                .expect("validated template layer");
            outputs
                .entry(layer)
                .or_default()
                .insert_file(&destination)?;
            publication_bytes = publication_bytes
                .checked_add(bytes.len() as u64)
                .ok_or_else(|| anyhow::anyhow!("Initialization staging size overflow"))?;
        }
        let scaffolds = default_scaffolds();
        for bytes in scaffolds.values() {
            publication_bytes = publication_bytes
                .checked_add(bytes.len() as u64)
                .ok_or_else(|| anyhow::anyhow!("Initialization staging size overflow"))?;
        }
        Ok(Self {
            project,
            templates,
            scaffolds,
            publication_bytes,
        })
    }
    pub fn project(&self) -> &ResolvedProject {
        &self.project
    }
    pub fn publication_bytes(&self) -> u64 {
        self.publication_bytes
    }
    pub fn templates(&self) -> &BTreeMap<PortableRelPath, Vec<u8>> {
        &self.templates
    }
    pub fn scaffolds(&self) -> &BTreeMap<ManagedPath, Vec<u8>> {
        &self.scaffolds
    }
}

fn default_scaffolds() -> BTreeMap<ManagedPath, Vec<u8>> {
    [
        (
            ManagedPath::Scaffold(ProjectScaffold::GitIgnore),
            include_bytes!("initialize/gitignore").as_slice(),
        ),
        (
            ManagedPath::Scaffold(ProjectScaffold::ValidationWorkflow),
            include_bytes!("initialize/validate.yml").as_slice(),
        ),
        (
            ManagedPath::Scaffold(ProjectScaffold::ReleaseWorkflow),
            include_bytes!("initialize/release.yml").as_slice(),
        ),
        (
            ManagedPath::Content {
                layer: empack_core::model::ContentLayer::Common,
                path: PortableRelPath::parse(".packwizignore", PathSyntax::ProjectContent)
                    .expect("embedded ignore path"),
            },
            include_bytes!("initialize/packwizignore").as_slice(),
        ),
    ]
    .into_iter()
    .map(|(path, bytes)| (path, bytes.to_vec()))
    .collect()
}
/// Editable data templates retain expressions until build-time metadata is known.
/// Build recipes already supply the current installer and launch scripts.
pub fn default_templates() -> BTreeMap<PortableRelPath, Vec<u8>> {
    [
        (
            "client/instance.cfg.template",
            include_bytes!("../../templates/client/instance.cfg.template").as_slice(),
        ),
        (
            "server/server.properties.template",
            include_bytes!("../../templates/server/server.properties.template").as_slice(),
        ),
    ]
    .into_iter()
    .map(|(name, bytes)| {
        (
            PortableRelPath::parse(name, PathSyntax::ProjectContent)
                .expect("embedded template path"),
            bytes.to_vec(),
        )
    })
    .collect()
}
