//! Exact Forge-family installer selection and bounded, independently parsed output contracts.
//! An installer plan is not a prepared runtime; execution and observed-output checks are separate.
use super::*;
use crate::empack::versions::{canonicalize_forge_loader_version, uses_legacy_forge_coordinate};
use crate::engine::{acquisition::TransferError, layout::CollisionIndex};
use empack_core::digest::ExpectedDigest;
use serde_json::Value;
use sha2::{Digest, Sha256};

#[derive(Debug, Clone)]
pub struct InstallerIdentity {
    pub coordinate: String,
    pub url: String,
    profile_version: Option<String>,
}
impl InstallerIdentity {
    pub fn for_runtime(runtime: &RuntimeResolution) -> Result<Self> {
        let game = runtime.minecraft.as_str();
        let loader = runtime
            .loader_version
            .as_ref()
            .context("Installer needs an exact loader")?
            .as_str();
        let (repository, group, artifact, version, profile_version) = match runtime.loader {
            LoaderKind::Forge => {
                let loader = canonicalize_forge_loader_version(game, loader);
                let version = if uses_legacy_forge_coordinate(game, &loader) {
                    format!("{game}-{loader}-{game}")
                } else {
                    format!("{game}-{loader}")
                };
                (
                    "https://maven.minecraftforge.net/",
                    "net.minecraftforge",
                    "forge",
                    version,
                    Some(format!("{game}-forge-{loader}")),
                )
            }
            LoaderKind::NeoForge if game == "1.20.1" => (
                "https://maven.neoforged.net/releases/",
                "net.neoforged",
                "forge",
                format!("{game}-{loader}"),
                Some(format!("{game}-forge-{loader}")),
            ),
            LoaderKind::NeoForge => (
                "https://maven.neoforged.net/releases/",
                "net.neoforged",
                "neoforge",
                loader.to_owned(),
                Some(format!("neoforge-{loader}")),
            ),
            _ => anyhow::bail!("Loader does not use a Forge-family installer"),
        };
        let coordinate = format!("{group}:{artifact}:{version}");
        let relative = maven_path(&format!("{coordinate}:installer"))?;
        Ok(Self {
            coordinate,
            url: format!("{repository}{}", relative.as_str()),
            profile_version,
        })
    }
}

#[derive(Debug, Clone)]
pub struct InstallerLibrary {
    pub coordinate: String,
    pub path: PortableRelPath,
    pub expected: ExpectedContent,
    /// An empty download field describes embedded or generated bytes, never an empty URL.
    pub download: Option<String>,
    pub checksum_documents: Vec<ContentId>,
    /// Historical profiles accept any one of these SHA-1 values, not all simultaneously.
    pub acceptable_sha1: Vec<ExpectedDigest>,
}
#[derive(Debug, Clone)]
pub enum InstallerLayout {
    /// Modern launch contracts carry both host argument files from the verified installer.
    Arguments {
        unix: Vec<u8>,
        windows: Vec<u8>,
        directory: PortableRelPath,
    },
    /// Historical profiles extract a universal executable JAR instead of generating run scripts.
    ExecutableJar {
        member: PortableRelPath,
        destination: PortableRelPath,
    },
}
#[derive(Debug, Clone)]
pub struct InstallerContract {
    pub runtime: RuntimeResolution,
    pub identity: InstallerIdentity,
    pub profile: ContentId,
    pub layout: InstallerLayout,
    pub minecraft_path: PortableRelPath,
    pub libraries: Vec<InstallerLibrary>,
    /// Server processor output assertions, when the upstream profile declares them.
    pub generated: BTreeMap<PortableRelPath, ExpectedContent>,
}
pub struct InstallerServerPlan {
    contract: InstallerContract,
    installer: AcquiredContent,
    expected: ExpectedContent,
    checksum_document: ContentId,
}
impl InstallerServerPlan {
    pub fn contract(&self) -> &InstallerContract {
        &self.contract
    }
    pub fn installer(&self) -> &AcquiredContent {
        &self.installer
    }
    pub fn expected(&self) -> &ExpectedContent {
        &self.expected
    }
    pub fn checksum_document(&self) -> ContentId {
        self.checksum_document.clone()
    }

    pub async fn resolve(
        transport: &HttpAcquisition,
        scope: &mut WorkScope,
        runtime: RuntimeResolution,
        transfer: TransferLimits,
        archive: ArchiveLimits,
        policy: SourceEvidencePolicy,
    ) -> Result<Self> {
        let identity = InstallerIdentity::for_runtime(&runtime)?;
        let (digest, checksum_document) =
            repository_digest(transport, scope, &identity.url, transfer).await?;
        let expected = ExpectedContent {
            digests: Some(DigestSet::new(vec![digest])?),
            size: None,
            accepted_observation: None,
        };
        let installer = transport
            .acquire(
                scope,
                DownloadRequest {
                    alternatives: NonEmpty::new(vec![identity.url.clone()])?,
                    expected: expected.clone(),
                    limits: transfer,
                    evidence: policy,
                    initial: InitialObservation::RequireEvidence,
                },
            )
            .await?;
        let content = installer.clone();
        let worker =
            scope.spawn_blocking(metadata_work(), ResourceRequest::default(), move |cancel| {
                InstallerContract::parse(runtime, identity, &content, archive, &cancel)
            })?;
        let contract = scope
            .accept(worker.wait().await?)?
            .transpose()?
            .into_parts()
            .0;
        Ok(Self {
            contract,
            installer,
            expected,
            checksum_document,
        })
    }
}

impl InstallerContract {
    fn parse(
        runtime: RuntimeResolution,
        identity: InstallerIdentity,
        content: &AcquiredContent,
        limits: ArchiveLimits,
        cancel: &Cancellation,
    ) -> Result<Self> {
        let mut jar = JarReader::open(content, limits, cancel)?;
        let profile_bytes = member(&mut jar, "install_profile.json", 16 << 20, cancel)?;
        let profile: Value = serde_json::from_slice(&profile_bytes)?;
        let (configuration, version, layout) = if profile.get("install").is_some() {
            let install = &profile["install"];
            ensure!(
                install["minecraft"] == runtime.minecraft.as_str()
                    && install["path"] == identity.coordinate,
                "Historical installer differs from selected runtime"
            );
            ensure!(
                profile["versionInfo"]["inheritsFrom"] == runtime.minecraft.as_str(),
                "Historical version metadata differs from game"
            );
            let name = install["filePath"]
                .as_str()
                .context("Historical installer lacks executable member")?;
            let member = path(name)?;
            ensure!(
                member.components().count() == 1 && name.ends_with(".jar"),
                "Historical installer executable is not a root JAR"
            );
            let destination = member.clone();
            (
                install.clone(),
                profile["versionInfo"].clone(),
                InstallerLayout::ExecutableJar {
                    member,
                    destination,
                },
            )
        } else {
            ensure!(
                matches!(profile["spec"].as_u64(), Some(0 | 1)),
                "Unsupported installer profile version"
            );
            ensure!(
                profile["minecraft"] == runtime.minecraft.as_str()
                    && profile["version"].as_str() == identity.profile_version.as_deref(),
                "Installer profile differs from selected runtime"
            );
            let json = profile["json"]
                .as_str()
                .context("Installer lacks version document")?;
            let version: Value = serde_json::from_slice(&member(
                &mut jar,
                json.strip_prefix('/').unwrap_or(json),
                16 << 20,
                cancel,
            )?)?;
            ensure!(
                version["inheritsFrom"] == runtime.minecraft.as_str()
                    && version["id"] == profile["version"],
                "Installer version document differs from runtime"
            );
            let layout = if let Some(contained) = profile["path"].as_str() {
                ensure!(
                    contained == identity.coordinate,
                    "Installer executable differs from selected loader"
                );
                let relative = maven_path(contained)?;
                let member = path(&format!("maven/{}", relative.as_str()))?;
                let destination = path(
                    relative
                        .as_str()
                        .rsplit('/')
                        .next()
                        .expect("nonempty coordinate"),
                )?;
                InstallerLayout::ExecutableJar {
                    member,
                    destination,
                }
            } else {
                let relative = maven_path(&identity.coordinate)?;
                let parent = relative.as_str().rsplit_once('/').expect("Maven parent").0;
                InstallerLayout::Arguments {
                    unix: member(&mut jar, "data/unix_args.txt", 1 << 20, cancel)?,
                    windows: member(&mut jar, "data/win_args.txt", 1 << 20, cancel)?,
                    directory: path(&format!("libraries/{parent}"))?,
                }
            };
            (profile.clone(), version, layout)
        };
        if let InstallerLayout::ExecutableJar { member: file, .. } = &layout {
            let entry = jar
                .archive
                .by_name(file.as_str())
                .context("Installer omits declared executable")?;
            ensure!(
                !entry.is_dir() && !entry.encrypted() && entry.size() > 0,
                "Invalid installer executable"
            );
        }
        let minecraft_path = server_path(
            configuration["serverJarPath"].as_str(),
            runtime.minecraft.as_str(),
        )?;
        let mut libraries = BTreeMap::new();
        let has_server_tasks = profile["processors"].as_array().is_some_and(|processors| {
            processors.iter().any(|processor| {
                processor.get("sides").is_none()
                    || processor["sides"]
                        .as_array()
                        .is_some_and(|sides| sides.iter().any(|side| side == "server"))
            })
        });
        let preparation_libraries = has_server_tasks
            .then(|| configuration.get("libraries"))
            .flatten();
        for value in [preparation_libraries, version.get("libraries")]
            .into_iter()
            .flatten()
        {
            let entries = value
                .as_array()
                .context("Installer libraries must be an array")?;
            ensure!(
                entries.len() <= 2048,
                "Installer library count exceeds limit"
            );
            for entry in entries {
                cancel.check()?;
                if profile.get("install").is_some() && entry["serverreq"] != true {
                    continue;
                }
                let mut library = parse_library(entry)?;
                if library.coordinate == identity.coordinate
                    && let InstallerLayout::ExecutableJar { destination, .. } = &layout
                {
                    library.path = destination.clone();
                }
                if let Some(previous) = libraries.insert(library.path.clone(), library.clone()) {
                    ensure!(
                        previous.coordinate == library.coordinate
                            && previous.expected == library.expected
                            && previous.download == library.download
                            && previous.acceptable_sha1 == library.acceptable_sha1,
                        "Installer has conflicting library declarations"
                    );
                }
            }
        }
        let mut collisions = CollisionIndex::default();
        for path in libraries.keys() {
            collisions.insert_file(path)?;
        }
        let generated = generated_assertions(&profile, runtime.minecraft.as_str())?;
        Ok(Self {
            runtime,
            identity,
            profile: ContentId::from_sha256(Sha256::digest(&profile_bytes).into()),
            layout,
            minecraft_path,
            libraries: libraries.into_values().collect(),
            generated,
        })
    }
}
fn path(value: &str) -> Result<PortableRelPath> {
    Ok(PortableRelPath::parse(value, PathSyntax::ArchiveMember)?)
}
fn member(jar: &mut JarReader, name: &str, maximum: u64, cancel: &Cancellation) -> Result<Vec<u8>> {
    path(name)?;
    let mut entry = jar
        .archive
        .by_name(name)
        .with_context(|| format!("Installer omits {name}"))?;
    ensure!(
        !entry.is_dir() && !entry.encrypted() && entry.size() <= maximum,
        "Invalid installer document"
    );
    let mut bytes = Vec::new();
    crate::engine::io::copy_bounded(&mut entry, &mut bytes, maximum, cancel)?;
    Ok(bytes)
}
fn maven_path(coordinate: &str) -> Result<PortableRelPath> {
    let (coordinate, extension) = coordinate.split_once('@').unwrap_or((coordinate, "jar"));
    let parts = coordinate.split(':').collect::<Vec<_>>();
    let valid = |part: &str| {
        !part.is_empty()
            && part.len() <= 256
            && part
                .bytes()
                .all(|ch| ch.is_ascii_alphanumeric() || b"._-+".contains(&ch))
    };
    ensure!(
        (parts.len() == 3 || parts.len() == 4)
            && parts.iter().all(|part| valid(part))
            && valid(extension)
            && parts[0].split('.').all(|part| !part.is_empty()),
        "Invalid installer Maven coordinate"
    );
    let classifier = parts
        .get(3)
        .map(|value| format!("-{value}"))
        .unwrap_or_default();
    path(&format!(
        "{}/{}/{}/{}-{}{classifier}.{extension}",
        parts[0].replace('.', "/"),
        parts[1],
        parts[2],
        parts[1],
        parts[2]
    ))
}
fn parse_library(value: &Value) -> Result<InstallerLibrary> {
    let coordinate = value["name"]
        .as_str()
        .context("Installer library has no coordinate")?
        .to_owned();
    let relative = maven_path(&coordinate)?;
    ensure!(
        value.get("rules").is_none() && value.get("natives").is_none(),
        "Installer library has unsupported selection rules"
    );
    let artifact = &value["downloads"]["artifact"];
    let (download, expected) = if artifact.is_object() {
        ensure!(
            artifact["path"] == relative.as_str(),
            "Installer library path differs from coordinate"
        );
        let url = artifact["url"]
            .as_str()
            .context("Installer library lacks download disposition")?;
        if !url.is_empty() {
            validate_download_url(url)?;
        }
        let digest = ExpectedDigest::parse(
            "sha1",
            artifact["sha1"]
                .as_str()
                .context("Installer library lacks SHA-1")?,
        )?;
        let size = artifact["size"]
            .as_u64()
            .context("Installer library lacks size")?;
        ensure!(size > 0, "Installer library is empty");
        (
            (!url.is_empty()).then(|| url.to_owned()),
            ExpectedContent {
                digests: Some(DigestSet::new(vec![digest])?),
                size: Some(size),
                accepted_observation: None,
            },
        )
    } else {
        // Historical profiles publish coordinates without byte assertions. Acquisition must obtain
        // repository evidence before these can become runtime files.
        let repository = value["url"]
            .as_str()
            .unwrap_or("https://libraries.minecraft.net/");
        validate_download_url(repository)?;
        ensure!(
            repository.ends_with('/') && !repository.contains('?'),
            "Invalid historical library repository"
        );
        (
            Some(format!("{repository}{}", relative.as_str())),
            ExpectedContent {
                digests: None,
                size: None,
                accepted_observation: None,
            },
        )
    };
    let acceptable_sha1 = match value.get("checksums") {
        None => Vec::new(),
        Some(checksums) => {
            let checksums = checksums
                .as_array()
                .context("Invalid legacy library checksums")?;
            ensure!(
                !checksums.is_empty() && checksums.len() <= 32,
                "Invalid legacy checksum alternatives"
            );
            checksums
                .iter()
                .map(|value| {
                    Ok(ExpectedDigest::parse(
                        "sha1",
                        value.as_str().context("Invalid checksum alternative")?,
                    )?)
                })
                .collect::<Result<Vec<_>>>()?
        }
    };
    Ok(InstallerLibrary {
        coordinate,
        path: path(&format!("libraries/{}", relative.as_str()))?,
        expected,
        download,
        checksum_documents: Vec::new(),
        acceptable_sha1,
    })
}
fn server_path(template: Option<&str>, game: &str) -> Result<PortableRelPath> {
    let value = template
        .map(|text| {
            text.replace("{LIBRARY_DIR}", "libraries")
                .replace("{MINECRAFT_VERSION}", game)
                .replace("{ROOT}/", "")
        })
        .unwrap_or_else(|| format!("minecraft_server.{game}.jar"));
    ensure!(!value.contains(['{', '}']), "Unknown server path token");
    path(&value)
}
fn generated_assertions(
    profile: &Value,
    game: &str,
) -> Result<BTreeMap<PortableRelPath, ExpectedContent>> {
    let mut result = BTreeMap::new();
    let Some(processors) = profile.get("processors") else {
        return Ok(result);
    };
    let processors = processors.as_array().context("Invalid processor list")?;
    ensure!(processors.len() <= 512, "Too many installer processors");
    for processor in processors {
        if let Some(sides) = processor.get("sides") {
            let sides = sides.as_array().context("Invalid processor sides")?;
            ensure!(
                sides
                    .iter()
                    .all(|side| matches!(side.as_str(), Some("client" | "server"))),
                "Unknown processor side"
            );
            if !sides.iter().any(|side| side == "server") {
                continue;
            }
        }
        let Some(outputs) = processor.get("outputs") else {
            continue;
        };
        for (output, hash) in outputs.as_object().context("Invalid processor outputs")? {
            let expand = |value: &str| -> Result<String> {
                if let Some(key) = value
                    .strip_prefix('{')
                    .and_then(|key| key.strip_suffix('}'))
                {
                    Ok(profile["data"][key]["server"]
                        .as_str()
                        .context("Unknown server output token")?
                        .to_owned())
                } else {
                    Ok(value.to_owned())
                }
            };
            let output = expand(output)?;
            let output = if let Some(coordinate) = output
                .strip_prefix('[')
                .and_then(|value| value.strip_suffix(']'))
            {
                path(&format!("libraries/{}", maven_path(coordinate)?.as_str()))?
            } else {
                server_path(Some(&output), game)?
            };
            let hash = expand(hash.as_str().context("Invalid processor hash")?)?;
            let hash = hash
                .strip_prefix('\'')
                .and_then(|hash| hash.strip_suffix('\''))
                .unwrap_or(&hash);
            let expected = ExpectedContent {
                digests: Some(DigestSet::new(vec![ExpectedDigest::parse("sha1", hash)?])?),
                size: None,
                accepted_observation: None,
            };
            if let Some(previous) = result.insert(output, expected.clone()) {
                ensure!(previous == expected, "Conflicting processor output hashes");
            }
        }
    }
    if let Some(data) = profile.get("data") {
        for (key, value) in data.as_object().context("Invalid installer data")? {
            let value = value["server"]
                .as_str()
                .context("Installer data omits server value")?;
            if let Some(coordinate) = value
                .strip_prefix('[')
                .and_then(|value| value.strip_suffix(']'))
            {
                let path = path(&format!("libraries/{}", maven_path(coordinate)?.as_str()))?;
                let digest = profile["data"][format!("{key}_SHA")]["server"]
                    .as_str()
                    .map(|hash| {
                        ExpectedDigest::parse(
                            "sha1",
                            hash.strip_prefix('\'')
                                .and_then(|hash| hash.strip_suffix('\''))
                                .unwrap_or(hash),
                        )
                    })
                    .transpose()?;
                let expected = ExpectedContent {
                    digests: digest
                        .map(|digest| DigestSet::new(vec![digest]))
                        .transpose()?,
                    size: None,
                    accepted_observation: None,
                };
                if let Some(previous) = result.get(&path) {
                    ensure!(
                        expected.digests.is_none() || previous.digests == expected.digests,
                        "Conflicting generated byte assertions"
                    );
                } else {
                    result.insert(path, expected);
                }
            }
        }
    }
    Ok(result)
}

mod execution;
pub use execution::{InstallerExecution, InstallerRuntimeEvidence};

#[cfg(test)]
mod tests;

async fn repository_digest(
    transport: &HttpAcquisition,
    scope: &mut WorkScope,
    url: &str,
    transfer: TransferLimits,
) -> Result<(ExpectedDigest, ContentId)> {
    let mut assertion = None;
    for algorithm in ["sha256", "sha1", "md5"] {
        let document = match library::metadata_document(
            transport,
            scope,
            format!("{}.{}", url, algorithm),
            4096,
            transfer,
        )
        .await
        {
            Ok(document) => document,
            Err(error)
                if error
                    .downcast_ref::<TransferError>()
                    .is_some_and(|error| matches!(error, TransferError::NotFound)) =>
            {
                continue;
            }
            Err(error) => return Err(error),
        };
        let id = document.lease().id();
        let worker = scope.spawn_blocking(
            metadata_work(),
            ResourceRequest::default(),
            move |_| -> Result<_> {
                let mut text = String::new();
                document.lease().open().read_to_string(&mut text)?;
                let digest = ExpectedDigest::parse(
                    algorithm,
                    text.split_whitespace()
                        .next()
                        .context("Empty installer checksum")?,
                )?;
                Ok((digest, id))
            },
        )?;
        assertion = Some(
            scope
                .accept(worker.wait().await?)?
                .transpose()?
                .into_parts()
                .0,
        );
        break;
    }
    assertion.context("Repository publishes no supported digest")
}
